name: Process JSON

on:
  push:
    paths:
      - 'TVBoxOSC/tvbox/api.json'
  workflow_dispatch:

jobs:
  process-json:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Process JSON
        run: |
          import json
          import os
          
          # 读取源文件
          with open('TVBoxOSC/tvbox/api.json', 'r', encoding='utf-8') as f:
              data = json.load(f)
          
          # 需要移除的key列表  
          remove_keys = ['预告', '本地', '配置中心', '小斑快映', '玩偶哥哥', '木偶', '蜡笔', '至臻', '多多', '欧哥', '二小', '虎斑', '雷鲸', '海绵', '夸父', '趣盘']
          
          # 过滤sites列表
          data['sites'] = [site for site in data['sites'] if site['key'] not in remove_keys]
          
          # 读取live.json文件内容
          try:
              with open('TVBoxOSC/tvbox/live.json', 'r', encoding='utf-8') as f:
                  live_data = json.load(f)
                  
              # 添加live内容到json中
              if 'lives' not in data:
                  data['lives'] = []
              
              # 将live.json的内容合并到主json文件中
              if isinstance(live_data, list):
                  data['lives'].extend(live_data)
              elif isinstance(live_data, dict):
                  data['lives'].append(live_data)
                  
          except FileNotFoundError:
              print("live.json file not found, skipping live content addition")
          except json.JSONDecodeError:
              print("Error: live.json is not a valid JSON file")
          except Exception as e:
              print(f"Error processing live.json: {str(e)}")
          
          # 写入新文件
          with open('TVBoxOSC/tvbox/xs.json', 'w', encoding='utf-8') as f:
              json.dump(data, f, ensure_ascii=False, indent=4)
        shell: python

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add TVBoxOSC/tvbox/xs.json
          git commit -m "自动更新 xs.json"
          git push
