name: Download and Update Files

on:
  # 允许手动触发
  workflow_dispatch:
  # 定时运行
  schedule:
        - cron: '0 0 * * *'  # 每天运行一次

jobs:
  download-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and extract file
        run: |
          # 创建临时目录
          mkdir -p temp_download
          cd temp_download
          
          # 下载文件
          echo "开始下载文件..."
          curl -L -o "single_line.zip" "https://gitee.com/PizazzXS/another-d/raw/master/单线路.zip"
          
          if [ -f "single_line.zip" ]; then
            echo "文件下载成功，开始解压..."
            # 解压到项目根目录，覆盖现有文件
            unzip -o single_line.zip -d ../
            echo "文件解压完成"
          else
            echo "文件下载失败"
            exit 1
          fi
          
          # 清理临时文件
          cd ..
          rm -rf temp_download

      - name: Check and commit changes
        id: commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "检测到文件变更，提交更新..."
            git add .
            git commit -m "Update: 更新单线路文件 $(date '+%Y-%m-%d %H:%M:%S')"
            git push
            echo "更新已推送到仓库"
            echo "::set-output name=changes_detected::true"
          else
            echo "没有检测到文件变更"
            echo "::set-output name=changes_detected::false"
          fi

      - name: Trigger process-json workflow
        if: steps.commit.outputs.changes_detected == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: process-json.yml
          token: ${{ secrets.GITHUB_TOKEN }}
